[Partition]
Type=root
MountPoint=/
Label=arcex-root
Format=btrfs
CopyFiles=/:/
ExcludeFiles=/usr
MakeDirectories=/var /var/lib/extensions /nix /home
Subvolumes=/etc /var /nix:nodatacow /home
SizeMinBytes=1G
Compression=zstd
AddValidateFS=no
